DROP DATABASE IF EXISTS CookInc;

CREATE DATABASE CookInc;

USE CookInc;


#CRIAÇÃO DAS TABELAS


CREATE TABLE USUARIO (
    senha VARCHAR(30) NOT NULL,
    nome_completo VARCHAR(100) NOT NULL,
    id_usuario INT PRIMARY KEY,
    link_imagem VARCHAR(100),
    data_nasc DATE NOT NULL,
    FK_SEXO_id_sexo INT,
    FK_ENDERECO_id_endereco INT
);

CREATE TABLE RECEITA (
    imagem varchar(50) NOT NULL,
    modo_de_preparo VARCHAR(1000) NOT NULL,
    porcoes int NOT NULL,
    id_rec INT PRIMARY KEY,
    video_tutorial VARCHAR(1000),
    nome varchar(50) NOT NULL,
    FK_USUARIO_id_usuario INT,
    FK_CATEGORIA_id_cat INT,
    FK_TEMPO_DE_PREPARO_id_tempo INT
);

CREATE TABLE COMENTARIO (
    texto VARCHAR(1000)  NOT NULL,
    id_coment INT PRIMARY KEY,
    data_hora TIMESTAMP,
    FK_RECEITA_id_rec INT,
    FK_USUARIO_id_usuario INT
);

CREATE TABLE CATEGORIA (
    id_cat INT PRIMARY KEY,
    nome varchar(50) NOT NULL
);

CREATE TABLE SEXO (
    id_sexo INT PRIMARY KEY,
    tipo VARCHAR(9) NOT NULL
);

CREATE TABLE SUB_COMENTARIO (
    id_sub_coment INT PRIMARY KEY,
    texto VARCHAR(1000),
    FK_COMENTARIO_id_coment INT,
    FK_USUARIO_id_usuario INT
);

CREATE TABLE ENDERECO (
    complemento VARCHAR(50),
    numero VARCHAR(50),
    id_endereco INT PRIMARY KEY,
    cep INT,
    FK_LOGADOURO_id_logadouro INT 
);

CREATE TABLE INGREDIENTE (
    id_ingrediente INT PRIMARY KEY,
    nome varchar(100) NOT NULL,
    quantidade INT,
    FK_MEDIDA_id_medida INT
);

CREATE TABLE TAG (
    id_tag INT PRIMARY KEY,
    nomeTag VARCHAR(50)
);

CREATE TABLE ESTADO_UF (
    id_estado INT PRIMARY KEY,
    uf CHAR(2) NOT NULL
);

CREATE TABLE MUNICIPIO (
    id_municipio INT  PRIMARY KEY,
    nome VARCHAR(50)
);

CREATE TABLE BAIRRO (
    id_bairro INT  PRIMARY KEY,
    nome VARCHAR(50),
    FK_MUNICIPIO_id_municipio INT 
);

CREATE TABLE LOGADOURO (
    id_logadouro INT  PRIMARY KEY,
    nome VARCHAR(50),
    FK_BAIRRO_id_bairro INT 
);

CREATE TABLE MEDIDA (
    id_medida INT PRIMARY KEY,
    medida VARCHAR(30) NOT NULL
);

CREATE TABLE TEMPO_DE_PREPARO (
    id_tempo INT PRIMARY KEY,
    tempo VARCHAR(30)
);

CREATE TABLE TIPO_CONTATO (
    id_tipo INT PRIMARY KEY,
    tipo VARCHAR(100) NOT NULL
);

CREATE TABLE CONTATO (
	texto VARCHAR(500),
    FK_USUARIO_id_usuario INT,
    FK_TIPO_CONTATO_id_tipo INT
);

CREATE TABLE VOTOS (
    data_hora timestamp,
    FK_USUARIO_id_usuario INT,
    FK_RECEITA_id_rec INT,
    FK_TIPO_VOTO_id int
);

CREATE TABLE TIPO_VOTO (
    id int PRIMARY KEY,
    tipo varchar(20)
);

CREATE TABLE SEGUE (
    FK_USUARIO_id_usuario INT,
    FK_USUARIO_id_usuario_ INT
);

CREATE TABLE RECEITA_INGREDIENTE (
    FK_INGREDIENTE_id_ingrediente INT,
    FK_RECEITA_id_rec INT
);

CREATE TABLE RECEITA_TAG (
    FK_RECEITA_id_rec INT,
    FK_TAG_id_tag INT
);

CREATE TABLE MUNICIPIO_ESTADO (
    FK_MUNICIPIO_id_municipio INT ,
    FK_ESTADO_UF_id_estado INT
);

CREATE TABLE FAVORITO (
    FK_RECEITA_id_rec INT,
    FK_USUARIO_id_usuario INT
);
 
ALTER TABLE USUARIO ADD CONSTRAINT FK_USUARIO_1
    FOREIGN KEY (FK_SEXO_id_sexo)
    REFERENCES SEXO (id_sexo)
    ON DELETE RESTRICT ON UPDATE RESTRICT;
 
ALTER TABLE USUARIO ADD CONSTRAINT FK_USUARIO_2
    FOREIGN KEY (FK_ENDERECO_id_endereco)
    REFERENCES ENDERECO (id_endereco)
    ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE RECEITA ADD CONSTRAINT FK_RECEITA_1
    FOREIGN KEY (FK_USUARIO_id_usuario)
    REFERENCES USUARIO (id_usuario)
    ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE RECEITA ADD CONSTRAINT FK_RECEITA_2
    FOREIGN KEY (FK_CATEGORIA_id_cat)
    REFERENCES CATEGORIA (id_cat)
    ON DELETE RESTRICT ON UPDATE RESTRICT;
 
ALTER TABLE RECEITA ADD CONSTRAINT FK_RECEITA_3
    FOREIGN KEY (FK_TEMPO_DE_PREPARO_id_tempo)
    REFERENCES TEMPO_DE_PREPARO (id_tempo)
    ON DELETE RESTRICT ON UPDATE RESTRICT;
 
ALTER TABLE COMENTARIO ADD CONSTRAINT FK_COMENTARIO_1
    FOREIGN KEY (FK_RECEITA_id_rec)
    REFERENCES RECEITA (id_rec)
    ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE COMENTARIO ADD CONSTRAINT FK_COMENTARIO_2
    FOREIGN KEY (FK_USUARIO_id_usuario)
    REFERENCES USUARIO (id_usuario)
    ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE SUB_COMENTARIO ADD CONSTRAINT FK_SUB_COMENTARIO_1
    FOREIGN KEY (FK_COMENTARIO_id_coment)
    REFERENCES COMENTARIO (id_coment)
    ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE SUB_COMENTARIO ADD CONSTRAINT FK_SUB_COMENTARIO_2
    FOREIGN KEY (FK_USUARIO_id_usuario)
    REFERENCES USUARIO (id_usuario)
    ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE ENDERECO ADD CONSTRAINT FK_ENDERECO_1
    FOREIGN KEY (FK_LOGADOURO_id_logadouro)
    REFERENCES LOGADOURO (id_logadouro)
    ON DELETE RESTRICT ON UPDATE RESTRICT;
 
ALTER TABLE INGREDIENTE ADD CONSTRAINT FK_INGREDIENTE_1
    FOREIGN KEY (FK_MEDIDA_id_medida)
    REFERENCES MEDIDA (id_medida)
    ON DELETE RESTRICT ON UPDATE RESTRICT;
 
ALTER TABLE BAIRRO ADD CONSTRAINT FK_BAIRRO_1
    FOREIGN KEY (FK_MUNICIPIO_id_municipio)
    REFERENCES MUNICIPIO (id_municipio)
    ON DELETE RESTRICT ON UPDATE RESTRICT;
 
ALTER TABLE LOGADOURO ADD CONSTRAINT FK_LOGADOURO_1
    FOREIGN KEY (FK_BAIRRO_id_bairro)
    REFERENCES BAIRRO (id_bairro)
    ON DELETE RESTRICT ON UPDATE RESTRICT;
 
ALTER TABLE CONTATO ADD CONSTRAINT FK_CONTATO_0
    FOREIGN KEY (FK_USUARIO_id_usuario)
    REFERENCES USUARIO (id_usuario)
    ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE CONTATO ADD CONSTRAINT FK_CONTATO_1
    FOREIGN KEY (FK_TIPO_CONTATO_id_tipo)
    REFERENCES TIPO_CONTATO (id_tipo)
    ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE VOTOS ADD CONSTRAINT FK_VOTOS_0
    FOREIGN KEY (FK_USUARIO_id_usuario)
    REFERENCES USUARIO (id_usuario)
    ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE VOTOS ADD CONSTRAINT FK_VOTOS_1
    FOREIGN KEY (FK_RECEITA_id_rec)
    REFERENCES RECEITA (id_rec)
    ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE VOTOS ADD CONSTRAINT FK_VOTOS_2
    FOREIGN KEY (FK_TIPO_VOTO_id)
    REFERENCES TIPO_VOTO (id)
    ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE SEGUE ADD CONSTRAINT FK_SEGUE_0
    FOREIGN KEY (FK_USUARIO_id_usuario)
    REFERENCES USUARIO (id_usuario)
    ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE SEGUE ADD CONSTRAINT FK_SEGUE_1
    FOREIGN KEY (FK_USUARIO_id_usuario_)
    REFERENCES USUARIO (id_usuario)
    ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE RECEITA_INGREDIENTE ADD CONSTRAINT FK_RECEITA_INGREDIENTE_0
    FOREIGN KEY (FK_INGREDIENTE_id_ingrediente)
    REFERENCES INGREDIENTE (id_ingrediente)
    ON DELETE RESTRICT ON UPDATE RESTRICT;
 
ALTER TABLE RECEITA_INGREDIENTE ADD CONSTRAINT FK_RECEITA_INGREDIENTE_1
    FOREIGN KEY (FK_RECEITA_id_rec)
    REFERENCES RECEITA (id_rec)
    ON DELETE RESTRICT ON UPDATE RESTRICT;
 
ALTER TABLE RECEITA_TAG ADD CONSTRAINT FK_RECEITA_TAG_0
    FOREIGN KEY (FK_RECEITA_id_rec)
    REFERENCES RECEITA (id_rec)
    ON DELETE RESTRICT ON UPDATE RESTRICT;
 
ALTER TABLE RECEITA_TAG ADD CONSTRAINT FK_RECEITA_TAG_1
    FOREIGN KEY (FK_TAG_id_tag)
    REFERENCES TAG (id_tag)
    ON DELETE SET NULL ON UPDATE CASCADE;
 
ALTER TABLE MUNICIPIO_ESTADO ADD CONSTRAINT FK_MUNICIPIO_ESTADO_0
    FOREIGN KEY (FK_MUNICIPIO_id_municipio)
    REFERENCES MUNICIPIO (id_municipio)
    ON DELETE RESTRICT ON UPDATE RESTRICT;
 
ALTER TABLE MUNICIPIO_ESTADO ADD CONSTRAINT FK_MUNICIPIO_ESTADO_1
    FOREIGN KEY (FK_ESTADO_UF_id_estado)
    REFERENCES ESTADO_UF (id_estado)
    ON DELETE RESTRICT ON UPDATE RESTRICT;
 
ALTER TABLE FAVORITO ADD CONSTRAINT FK_FAVORITO_0
    FOREIGN KEY (FK_RECEITA_id_rec)
    REFERENCES RECEITA (id_rec)
    ON DELETE SET NULL ON UPDATE CASCADE;
 
ALTER TABLE FAVORITO ADD CONSTRAINT FK_FAVORITO_1
    FOREIGN KEY (FK_USUARIO_id_usuario)
    REFERENCES USUARIO (id_usuario)
    ON DELETE SET NULL ON UPDATE CASCADE;
    
